name: Accessibility checks (Pa11y)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pa11y:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node, Pa11y and Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y npm
          npm install -g pa11y
          npm install puppeteer@latest

      - name: Run Pa11y on all HTML files
        run: |
          echo "Searching for all HTML files..."
          find $GITHUB_WORKSPACE -name "*.html" -print0 | while IFS= read -r -d '' file; do
            echo "------------------------------------------------------------"
            echo "Checking accessibility for: $file"
            echo "------------------------------------------------------------"
            pa11y "file://$file"
            echo "Done."
            echo
          done
