name: Accessibility checks (Pa11y)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pa11y:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node & Pa11y
        run: |
          sudo apt-get update
          sudo apt-get install -y npm
          npm install -g pa11y
          npm install puppeteer@latest

      - name: Run Pa11y with no-sandbox Chromium
        run: |
          pa11y file://$GITHUB_WORKSPACE/index.html --chrome-launcher-flags="--no-sandbox --disable-setuid-sandbox"
