name: W3C CSS Validation

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate_css:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run CSS Validator
        uses: Siilwyn/css-validator-action@v2
        with:
          path: "styles"
