name: W3C HTML Validation

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate_html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install HTML5 validator
        run: |
          sudo apt-get update
          sudo apt-get install -y npm
          sudo npm install -g vnu-jar

      - name: Run W3C validator
        run: vnu --skip-non-html --errors-only .
